# A database made by us. Each tuple contains the steps required to go from point A to point B, also the bearing relative to north as to where it is located.
edges = [('Gate 2','MPR Gate end', 54, 170),
('MPR Gate end','Reception', 27, 200),
('Reception','Reception stairs',15,210),
('Reception stairs','Student Center' ,15, 290),
('Reception','Reception Elevator ground',26,270),
('Reception', 'Office of career services', 30,280),
('Student Center','Reception washroom' ,16,180),
('Reception','Turnstile',14,175),
('Turnstile','MPR Library end',16,80),
('Turnstile','Library junction',40,178),
('Library junction','Office Of Student Life', 19,310),
('Office Of Student Life', 'Wellness Courtyard',24,310),
('Library junction', 'Cafe2go', 37,90),
('Library junction', 'Library Info Commons', 33,62),
('Cafe2go','Cassim lab',36,185),
('Cassim lab', 'East level 1 faculty pods', 13,175),
('East level 1 faculty pods', 'Easten ramp ground', 29,206),
('Library junction', 'Central street ground faculty pods',43,207),
('Central street ground faculty pods','Central street stairs ground', 42,207),
('Central street ground faculty pods', 'ATM', 34,170),
('Central street ground faculty pods', 'Arif Habib Classroom', 43,228),
('Arif Habib Classroom', 'Earth Courtyard',13,2),
('Earth Courtyard', 'Western stairs ground' ,24,27),
('Western stairs ground', 'Physics Lab' , 20,291),
('Physics Lab', 'Western elevator ground', 8,290),
('Western elevator Ground', 'Math lab', 8,190),
('Physics Lab', 'Earth Courtyard Boards', 20,200),
('Earth Courtyard Boards', 'Air Courtyard' ,20,200),
('Air Courtyard', 'Arif Habib Classroom', 22,80),
('Air Courtyard', 'Water Courtyard',17,170),
('Water Courtyard', 'Fire Courtyard' ,37,200),
('Fire Courtyard', 'Chemistry Lab',20,255),
('Fire Courtyard', 'Ecology Lab'  ,20,255),
('Digital Systems and Instrumentation Lab', 'Fire Courtyard',24,130),
('Communications lab', 'Fire Courtyard',24,130),
('Fire Courtyard', 'Student lounge Amphitheatre end' ,55,150),
('Student Lounge Amphitheatre end', 'Soorty Hall',47,70),
('Student Lounge Garden end','Soorty Hall',40,20),
('ATM', 'Soorty Hall' ,55,170),
('Soorty Hall','Student Lounge Garden end',38,211),
('Student Lounge Garden end' ,'Courts adjacent Faculty pods',20,180),
('Courts adjacent Faculty pods', 'Multipurpose Sports Courts 1' ,56,180),
('Multipurpose Sports Courts 1', 'Zen Garden' ,100,175),
('Multipurpose Sports Courts 1', 'Rahim bhai stall' ,80,30),
('Rahim Bhai stall', 'Dhaba' ,24,108),
('Rahim Bhai stall', 'Hu Dukaan' ,17,0),
('Hu Dukaan', 'Cafeteria Dukaan end',11,90),
('Hu Dukaan', 'Amphitheatre washroom' ,23,330),
('Amphitheatre washroom' , 'Amphitheatre lower' ,15,260),
('Amphitheatre lower', 'Amphitheatre upper' ,40,180),
('Amphitheatre upper', 'C-015' ,33,107),
('C-015', 'Gym' ,27,220),
('C-015', 'Swimming Pool',44,260),
('Swimming Pool', 'Facilities office',58,15),
('Facilities office', 'Changing room',44,96),
('Facilities office', 'Engineering Workshop',21,53),
('Facilities office', 'Western Elevator lower ground',65,355),
('C-015', 'Hu Dukaan',27,45),
('Cafeteria Dukaan end', 'Cafeteria Projects Lab end',35,12),
('Cafeteria Projects Lab end', 'Ground floor Projects Lab',25,2),
('Ground floor Projects Lab', 'Power lab',25,19),
('Power lab', 'Circuits and Electronic Lab 1',27,11),
('Circuits and Electronic Lab 1', 'Music Room',23,100),
('Music Room', 'Linux And Networking Lab',7,90),
('Linux And Networking Lab','Lower ground eastern washrooms',11,155),
('Lower ground eastern washrooms', 'Visualization And Graphics Lab',28,185),
('Visualization And Graphics Lab', 'Dinshaw Classroom', 10,180),
('Dinshaw Classroom', 'Rangoonwala Classroom', 6,180),
('Dinshaw Classroom', 'Easter ramp lower',15,230),
('Eastern ramp lower', 'Ground floor Projects Lab',31,290),
('Reception Elevator ground','Reception Elevator first',0,0),
('Reception Elevator first','Reception Elevator second',0,0),
('Reception Elevator second','Reception Elevator third',0,0),
('Western Elevator lower ground','Western Elevator ground',0,0),
('Western Elevator ground','Western Elevator first',0,0),
('Eastern ramp lower','Eastern ramp ground',84,0),
('Turnstile stairs ground','Turnstile',20,350),
('Turnstile stairs lower','Turnstile stairs ground',31,350),
('Turnstile stairs lower','Female Lounge',52,277),
('Female Lounge','Western stairs ground',30,175),
('Western pathway Air junction','Western pathway Wellness junction',59,4),
('Western pathway Wellness junction','Bank',81,9),
('Bank','Security office',20,18),
('Gate 2','Security office',70,280),
('ATM stairs','Tapal stairs',45,187),
('Tapal stairs','Hu Dukaan',13,177),
('Tapal stairs','Amphitheatre washroom',10,285),
('ATM','ATM stairs',13,190),
('Wellness Courtyard','Western pathway Wellness junction',47,285),
('Office Of Student Life','Wellness Courtyard',16,285),
('Central street stairs ground','Central street stairs top',24,33),
('Earth courtyard Ramp ground','Earth courtyard ramp first',90,180),
('Earth courtyard Ramp ground','Earth Courtyard',10,9),
('Western stairs ground', 'Western stairs first',49,15),
('Western stairs first', 'Western stairs second',69,15),
('Western stairs second','Western elevator second',20,268),
('Western elevator second','Second floor Ground floor Projects Lab',12,215),
('Western elevator second','Second floor faculty pods W-301-10',12,215),
('Western elevator second','W321',26,170),
('Reception stairs ground','Reception stairs first/ground junction',30,195),
('Reception stairs first/ground junction','Reception stairs first/second junction',25,15),
('Reception stairs first/second junction','Reception stairs second',30,230),
('Film Studio', 'Tariq Rafi Lecture Theater', 38, 260),
('Central street stairs top', 'Tariq Rafi Lecture Theater', 24, 90),
('Central street stairs top', 'W221 Faculty Pod', 49, 302),
('W221 Faculty Pod', 'W242', 30, 160),
('W221 Faculty Pod', 'W243', 47, 174),
('W242', 'W243', 17, 200),
('W242', 'Design Studio', 19, 60),
('W221 Faculty Pod', 'Western Elevator first', 12, 40),
('Western Elevator first', 'C203 Faculty Pod', 36, 140),
('C203 Faculty Pod', 'CPE C201', 51, 32),
('CPE C201', 'Library Entrance 1st Floor', 35, 100),
('CPE C201', 'CPE Classroom', 54,0),  # Audi Route
('CPE C201', 'CPE Classroom', 42,0),  # Deans Pod Route
('Library Entrance 1st Floor', 'Library Discussion Rooms', 34, 140),
('Library Entrance 1st Floor',  'Yohsin Hall', 40, 64),
('CPE Classroom', 'Deans Pod', 44, 300),
('CPE Classroom', 'Auditorium', 30, 80),
('CPE Classroom', 'Reception Elevator first', 12, 340),
('CPE Classroom', 'N219 faculty Pods', 19, 217),
('CPE Classroom', 'Standard Chartered Classroom', 28,317),
('CPE Classroom', 'N219 faculty Pods', 32, 350),
('Reception Staris first/ground junction', 'CPE C201', 26, 226),
('Reception Stairs first/second junction', 'Auditorium', 31, 200),
('Reception Stairs first/ground junction', 'CPE Classroom', 30, 330),
('Reception Stairs second', 'Playground',5, 55),
('Playground' , 'Second floor Admin offices', 35, 330),
('Second floor Admin offices', 'Reception Elevator second', 7,7),
('Library Entrance 1st Floor','Library Info commons',34,350),
('Library Info commons','Writing Centre',27,61),
('Library Info commons','Ehsas elevator ground',27,61),
('Ehsas elevator ground','Ehsas centre',0,0),
('Ehsas elevator ground','Yohsin Hall',0,0),
('Central street stairs ground','Central street stairs top',24,33),
('Earth courtyard Ramp ground','Earth courtyard ramp first',90,180),
('Earth courtyard Ramp ground','Earth Courtyard',10,9),
('Western stairs ground', 'Western stairs first',49,15),
('Western stairs first', 'Western stairs second',69,15),
('Western stairs second','Western elevator second',20,268),
('Western elevator second','Second floor Ground floor Projects Lab',12,215),
('Western elevator second','Second floor faculty pods W-301-10',12,215),
('Western elevator second','W-321',26,170),
('Reception stairs ground','Reception stairs first/ground junction',30,195),
('Reception stairs first/ground junction','Reception stairs first/second junction',25,15),
('Reception stairs first/second junction','Reception stairs second',30,230)]
edges1 = [('Gate 2','MPR outer', 54, 170),
('MPR outer','Reception desk', 27, 200),
('Reception desk','Reception stairs ground',15,210),
('Reception stairs ground','Student Centre' ,15, 290),
('Student Centre','Reception washroom' ,16,180),
('Reception desk','Reception Elevator ground',26,270),
('Reception desk', 'OCS', 30,280),
('Reception desk','Turnstile',14,175),
('Turnstile','MPR inner',16,80),
('Turnstile','Library junction',40,178),
('Library junction','Student life office', 19,310),
('Student life office', 'Health and Wellness',40,310),
('Library junction', 'Cafe2go', 37,90),
('Library junction', 'Library', 33,62),
('Cafe2go','Cassim lab',36,185),
('Cassim lab', 'East level 1 faculty pods', 13,175),
('East level 1 faculty pods', 'Easten ramp ground', 29,206),
('Library junction', 'Central street ground faculty pods',43,207),
('Central street ground faculty pods','Central street stairs ground', 42,207),
('Central street ground faculty pods', 'ATM', 34,170),
('Central street ground faculty pods', 'Arif Habib classroom', 43,228),
('Arif Habib classroom', 'Earth courtyard',13,2),
('Earth courtyard', 'Western stairs ground' ,24,27),
('Western stairs ground', 'Physics lab' , 20,291),
('Physics lab', 'Western elevator ground', 8,290),
('Physics lab', 'Math lab', 4,290),
('Western elevator Ground', 'Math lab', 8,190),
('Physics lab', 'Earth boards', 20,200),
('Earth boards', 'Air courtyard' ,20,200),
('Air courtyard', 'Arif Habib classroom', 22,80),
('Air courtyard', 'Water courtyard',17,170),
('Water courtyard', 'Fire courtyard' ,37,200),
('Fire courtyard', 'Chemistry lab',20,255),
('Fire courtyard', 'Ecology lab'  ,20,255),
('Digital systems lab', 'Fire courtyard',24,130),
('Communications lab', 'Fire courtyard',24,130),
('Fire courtyard', 'Student lounge amphi end' ,55,150),
('Student lounge amphi end', 'Soorty hall',47,70),
('ATM', 'Soorty hall' ,55,170),
('Soorty hall','Student lounge garden end',38,211),
('Student lounge garden end' ,'Courts Faculty pods',20,180),
('Courts Faculty pods', 'Courts' ,56,180),
('Courts', 'Zen garden',100,175)]
Edges = []
def out(edges,Edges):
    for i in edges:
        Edges.append(i)
        if len(i)==4:
            x = (i[1],i[0],i[2],(180 - i[3]))
        else:
            x = (i[1],i[0],i[2],(180 - i[3]))
        Edges.insert(Edges.index(i),x)
    return Edges

Edges = out(edges,Edges)
def addNodes(edges,w=[]):
    G={}
    for e in edges:
        if e[0] not in G:
            G[e[0]]=w
        if e[1] not in G:
            G[e[1]]=w
    return G
def addEdges(G,edges):
    for e in edges:
        try:
            G[e[0]]=G[e[0]]+[(e[1],e[2],e[3])]
            G[e[1]]=G[e[1]]+[(e[0],e[2],e[3])]
        except:
            pass
    return G
G1=addNodes(edges1)
addEdges(G1,edges1)
G=addNodes(Edges)
addEdges(G,Edges)

positions1=[('Gate 2', (5, 350)), ('MPR outer', (123, 309)), ('Reception desk', (184, 341)), ('Reception stairs ground', (222, 342)), 
('Student Centre', (203, 382)), ('Reception Elevator ground', (173, 410)), ('OCS', (143, 379)), ('Turnstile', (221, 321)), 
('MPR inner', (186, 305)),('Reception washroom',(258, 358)), ('Library junction', (344,290)), ('Student life office', (322, 401)),
('Health and Wellness', (315, 565)), ('Cafe2go', (317, 162)), ('Library', (264, 199)), ('Cassim lab', (403, 132)), 
('East level 1 faculty pods', (481, 131)), ('Easten ramp ground', (585, 170)), ('Central street ground faculty pods', (512, 367)), ('Central street stairs ground', (325,275)), ('ATM', (592, 288)), 
('Arif Habib classroom', (591, 420)), ('Earth courtyard', (555, 415)), 
('Western stairs ground', (518, 440)), ('Physics lab', (469, 458)), ('Western elevator ground', (481, 484)), ('Math lab', (511, 483)), 
('Earth boards', (541, 461)), ('Air courtyard', (605, 521)), ('Water courtyard', (644, 460)), ('Fire courtyard', (743, 482)), 
('Chemistry lab', (785, 473)), ('Ecology lab', (785, 489)), ('Digital systems lab', (711, 471)), ('Communications lab', (712, 487)), 
('Student lounge amphi end', (849, 342)), ('Soorty hall', (744, 273)), ('Student lounge garden end', (896, 302)), ('Courts Faculty pods', (936, 305)),
('Courts', (999, 297)), ('Zen garden', (1194, 208))]
